version: "3.8"


services:
  mongodb: # servei mongodb
    image: mongo:5.0.6 # imatge que s'instal·larà
    restart: always
    env_file: ./.env # arxiu on estan definides les variables d'entorn
    environment:
      # usuari i password amb accés a la bd
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
       # Ports d'accés a mongodb
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./men-app
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      # directori local que es replica en el container
      - ./men-app:/usr/src/webserver


volumes:
  db:
# Xarxa a la que es connectarà. Cal crear-la abans
networks:
  default:
    external:
      name: node-mongo